github: [thegoodeth12] # Replace with your actual GitHub Sponsors username
ko_fi: thegoodeth      # Optional, if you use Ko-fi (ko-fi.com/thegoodeth)
custom:
  - 'https://chatgtp-bot-reown.xyz/support'                       # Your SafeDashboard support hub
  - 'https://reown.com/support/thegoodeth'                        # Replace with your actual Reown support link
  - 'https://safe.global/address/0xAfD5f60aA8eb4F488eAA0eF98c1C5B0645D9A0A0' # Direct Safe wallet address
  - 'https://t.me/your_custom_bot?start=support_dashboard'        # Replace with your Telegram Mini App or support bot link
